services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8090:80
    volumes:
      - ./chroma:/data
    networks:
      - spacedev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=http://localhost:8090
    ports:
      - 8080:80

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - spacedev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # searxng:
  #   image: searxng/searxng:latest
  #   container_name: searxng
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./searxng:/etc/searxng
  #   restart: on-failure:3

networks:
  spacedev: