services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MODEL=llama3.1
      - EMBEDDING_MODEL=nomic-embed-text
    ports:
      - 8090:80
    volumes:
      - spacedev-chroma:/data
    networks:
      - spacedev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - spacedev

volumes:
  spacedev-chroma:

networks:
  spacedev: